export enum ETableName {
  USER = 'user',
  MESSAGE = 'message',
  CHAT = 'chat',
  PARTICIPANT = 'participant',
}

export const enum ETypeEvent {
  SCROLL_MESSAGE_LIST_TO = 'SCROLL_MESSAGE_LIST_TO',
  OPEN_LIST_CHAT = 'OPEN_LIST_CHAT',
  CLOSE_LIST_CHAT = 'CLOSE_LIST_CHAT',
  OPEN_MODAL_SEARCH_USER = 'OPEN_MODAL_SEARCH_USER',
  CLOSE_MODAL_SEARCH_USER = 'CLOSE_MODAL_SEARCH_USER',
}
